# Generated by Django 3.2.16 on 2024-08-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('إستشارة', 'إستشارة '), ('صفقة', ' صفقة')], default='إستشارة', max_length=255),
        ),
    ]
