# Generated by Django 5.0.7 on 2024-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20240804_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
